version: 0.1
env:
    secrets-manager:
      TOKEN: firstsecret:sonartoken
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=buggywebapp003 -Dsonar.organization=buggywebapp003 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=buggywebapp003 | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
        if [ $quality_status = "ERROR" ] ; then exit 1;fi