version: 0.1
env:
    secrets-manager:
      TOKEN: firstsecret:sonartoken
phases:
  build:
    commands:

#Static Application Security Scan (SAST scan) using SonarCloud
     - mvn verify sonar:sonar -Dsonar.projectKey=buggywebapp003 -Dsonar.organization=buggywebapp003 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN 

#Quality Gates for Static Application Security Scan(SAST) using SonarCloud

     - sleep 5
     - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=buggywebapp003 | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
#        if [ $quality_status = "ERROR" ] ; then exit 1;fi

#Software Composition Analysis Scan (SCA scan) using Snyk

     - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=75ef7e49-eb45-485f-b6c3-d142f22d9cd0
          export SNYK_TOKEN
          mvn snyk:test -fn 

#Dynamic Application Security Scan (DAST scan) using OWASP ZAP

     - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
        tar -xvf ZAP_2.12.0_Linux.tar.gz
        cd ZAP_2.12.0
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html 
        
#Storing DAST Reports in S3 bucket

artifacts:
  files:
    - zap_report.html